### ISSUE TITLE
Provide basic PHP 8.x support

### ISSUE THREAD

**Issue by defunctl** [mhcg/monolog-wp-cli#9]
**Describe the solution you'd like**
Updating the composer PHP version from `"php": "^7.2",` to `"php": ">=7.2"`, would at least allow this to be installed on PHP 8.x systems.

**Additional context _(Optional)_**
None

**Comment by markheydon** [comment]
You know what @defunctl, I actually thought I'd already done this a few weeks ago! I updated some of my other stuff to bring in-line with current WordPress requirements, somehow this one must have fell through the net. Will get it sorted shortly.

**Comment by defunctl** [comment]
@markheydon I forked this and did, would you like me to make a PR?

**Comment by markheydon** [comment]
> @markheydon I forked this and did it, would you like me to make a PR?

I've updated some of the unit test code as well so just created a PR myself. Haven't tested fully or reviewed the code as yet though, getting to it quick as I can.

**Comment by defunctl** [comment]
Oh sorry, didn't want to come across as if I was rushing you, was just offering to help/save you some time :)

**Comment by markheydon** [comment]
Not at all! Ordinarily I would have said, sure just open a PR, but when I looked at the code I realised it was way behind where it should be so thought try at least get some modernisations in there.

**Comment by markheydon** [comment]
Just checking @defunctl if your PHP 8 project working with the updated version?

**Comment by defunctl** [comment]
Hey @markheydon,

Unfortunately we were looking for php7.**2**+ support since our monorepo has not yet been updated to 7.4. But that's totally not your problem and something we're planning on doing anyways, so I'll just use my fork until we're able to get our monorepo updated and then revert back to this repo after.

Really appreciate you updating it, though!

**Comment by markheydon** [comment]
Ah! Guess you need to get (re)coding then, PHP 7.4 even goes EOL shortly! [PHP: Supported Versions](https://www.php.net/supported-versions.php)

**Comment by defunctl** [comment]
@markheydon definitely! I've begun the upgrade.

Might I suggest you delete the 1.2 tag/release here and on packagist and release it as 2.0.0 as the latest version is a breaking change release?

**Comment by markheydon** [comment]
@defunctl So decided to take your advise (sort of) and have rolled-back the PHP 7.4 specific version. In theory v1.3, which should be on Composer now, should work for PHP 7.2 and 7.3 but as there's little support anywhere in images, PHPUnit, etc. for the now EOL PHP 7.2 I cannot say for sure. I'll re-do a PHP 7.4+ version shortly as v2.

**Comment by defunctl** [comment]
@markheydon sounds great! This gave me the push anyways to get started on our upgrade as well, but I was just thinking of anyone with "^1.0" in their composer and still running legacy 7.2

Really appreciate the work and communication, let me know if you need a hand with anything.

**Comment by markheydon** [comment]
Time they upgraded to too 😏. I do agree that in hindsight I should have matched the major versions to those of Monolog, I plan to moving forward. So v3 will be Monolog v3 matched dependancy wise.
